# Generated by Django 6.1 on 2026-09-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('method', models.CharField(choices=[('jazzcash', 'JazzCash'), ('sadapay', 'SadaPay'), ('easypaisa', 'EasyPaisa'), ('bank', 'Bank Transfer')], max_length=20)),
                ('account_number', models.CharField(max_length=30)),
                ('account_title', models.CharField(blank=True, max_length=200)),
                ('instructions', models.TextField(blank=True, help_text='Extra instructions for students')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['method', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('jazzcash', 'JazzCash'), ('sadapay', 'SadaPay'), ('easypaisa', 'EasyPaisa'), ('online', 'Online'), ('free', 'Free')], default='free', max_length=20),
        ),
    ]
