# Generated by Django 6.1 on 2026-09-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meet_link',
            field=models.TextField(help_text='Google Meet / Zoom link'),
        ),
    ]
