# Generated by Django 6.1 on 2026-09-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubscription',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Whether this is a free trial subscription'),
        ),
        migrations.AddField(
            model_name='teachersubscription',
            name='trial_ends_at',
            field=models.DateField(blank=True, help_text='When the free trial expires', null=True),
        ),
    ]
