# Generated by Django 6.1 on 2026-09-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_seed_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.TextField(blank=True, help_text='One module per line'),
        ),
        migrations.AddField(
            model_name='course',
            name='faq',
            field=models.TextField(blank=True, help_text='Q: question | A: answer — one per line'),
        ),
        migrations.AddField(
            model_name='course',
            name='features',
            field=models.TextField(blank=True, help_text='One feature per line'),
        ),
        migrations.AddField(
            model_name='course',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description', max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description for cards', max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('quranic', 'Quranic Studies'), ('islamic', 'Islamic Studies'), ('arabic', 'Arabic Language'), ('personal', 'Personal Development'), ('kids', 'Kids Programs')], default='quranic', max_length=100),
        ),
    ]
