# Generated by Django 6.1 on 2026-09-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_curriculum_course_faq_course_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/%Y/%m/'),
        ),
    ]
